name: Test my_first_docker_action
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: UrPa/my_first_docker_action@v1
        with:
          who-to-greet: 'somebody'
